version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Uname
          command: python hello.py

